# kube-master
---
- name: "kube-master"
  resource_name: "kube-master"
  count: 3
  nodes:
    - nodename
  vm_id: 1001
  agent:
    enabled: true
    type: "virtio"
  bios: "seabios"
  ignore_changes:
    - "disks"
    - "cdrom"
  cpu:
    cores: 3
    sockets: 1
  cloud_init:
    type: "nocloud"
    interface: "ide0"
    datastore_id: "local-lvm"
    dns:
      domain: ""
      server: "1.1.1.1"
    ip_configs:
      - ipv4:
          address: "192.168.0.101/24"
          gateway: "192.168.0.1"
  clone:
    node_name: "nodename"
    vm_id: 1999
    full: true
  disks:
  memory:
    dedicated: 8192
  network_devices:
    - net1:
        bridge: "vmbr0"
        model: "virtio"
  on_boot: true
